const NetDAGDatabase = {
  products: {
    "NDG-FASHION-000001": {
      recordId: "NDG-REC-2026-000001",
      productId: "NDG-FASHION-000001",
      barcode: "NDG-FASHION-000001",
      name: "Nike Air Max 270",
      brand: "Nike",
      sku: "NDG-FASHION-000001",
      batch: "LOT-2026-0001",
      category: "Fashion",
      country: "Vietnam",
      origin: "Vietnam",
      manufacturer: "Nike Inc.",
      issuer: "NetDAG Provenance Desk",
      created: "2026-07-04",
      integrity: "Verified",
      trustStatus: "NETDAG_VERIFIED",
      onchainId: "NDG-FASHION-000001",
      guardianScore: 98,
      status: "VERIFIED",
      risk: "No Risk Detected",
      fraudStatus: "LOW",
      conflictFlag: false,
      reviewRequired: false,
      evidence: {
        barcode: "Scan",
        productName: "Manufacturer",
        manufacturer: "Manufacturer",
        origin: "Manufacturer",
        certificate: "NetDAG Provenance"
      },
      keywords: [
        "nike",
        "air max",
        "air max 270",
        "shoe",
        "sneaker",
        "fashion",
        "footwear"
      ]
    },

    "NDG-MED-000001": {
      recordId: "NDG-REC-2026-000002",
      productId: "NDG-MED-000001",
      barcode: "NDG-MED-000001",
      name: "SafeCure Paracetamol 500mg",
      brand: "SafeCure",
      sku: "NDG-MED-000001",
      batch: "MED-LOT-2026-441",
      category: "Medicine",
      country: "Germany",
      origin: "Germany",
      manufacturer: "SafeCure Pharma GmbH",
      issuer: "NetDAG Medicine Desk",
      created: "2026-07-04",
      integrity: "Verified",
      trustStatus: "TRUSTED_PRODUCT",
      onchainId: "NDG-MED-000001",
      guardianScore: 91,
      status: "VERIFIED",
      risk: "No Recall Detected",
      fraudStatus: "LOW",
      conflictFlag: false,
      reviewRequired: false,
      evidence: {
        barcode: "Scan",
        productName: "Database",
        manufacturer: "Label",
        batch: "QR Code",
        expiry: "Label OCR"
      },
      keywords: [
        "medicine",
        "paracetamol",
        "tablet",
        "500mg",
        "safecure",
        "pain relief"
      ]
    },

    "NDG-FOOD-000001": {
      recordId: "NDG-REC-2026-000003",
      productId: "NDG-FOOD-000001",
      barcode: "NDG-FOOD-000001",
      name: "Organic Cocoa Drink",
      brand: "PureFarm",
      sku: "NDG-FOOD-000001",
      batch: "FOOD-LOT-2026-118",
      category: "Food",
      country: "Ghana",
      origin: "Ghana",
      manufacturer: "PureFarm Foods Ltd.",
      issuer: "NetDAG Food Desk",
      created: "2026-07-04",
      integrity: "Evidence Confirmed",
      trustStatus: "EVIDENCE_CONFIRMED",
      onchainId: "NDG-FOOD-000001",
      guardianScore: 84,
      status: "WARNING",
      risk: "Moderate Sugar Level",
      fraudStatus: "LOW",
      conflictFlag: false,
      reviewRequired: false,
      evidence: {
        barcode: "Scan",
        productName: "Open Data",
        nutrition: "Label OCR",
        origin: "Label",
        manufacturer: "Label"
      },
      keywords: [
        "food",
        "cocoa",
        "drink",
        "organic",
        "purefarm",
        "ghana"
      ]
    },

    "NDG-ELEC-000001": {
      recordId: "NDG-REC-2026-000004",
      productId: "NDG-ELEC-000001",
      barcode: "NDG-ELEC-000001",
      name: "VoltX Smart Charger 65W",
      brand: "VoltX",
      sku: "NDG-ELEC-000001",
      batch: "ELEC-LOT-2026-072",
      category: "Electronics",
      country: "China",
      origin: "China",
      manufacturer: "VoltX Electronics Ltd.",
      issuer: "NetDAG Electronics Desk",
      created: "2026-07-04",
      integrity: "Auto Validated",
      trustStatus: "AUTO_VALIDATED",
      onchainId: "NDG-ELEC-000001",
      guardianScore: 76,
      status: "WARNING",
      risk: "Certification Evidence Limited",
      fraudStatus: "MEDIUM",
      conflictFlag: false,
      reviewRequired: true,
      evidence: {
        barcode: "Scan",
        productName: "User Submission",
        certification: "Pending Review",
        manufacturer: "Label"
      },
      keywords: [
        "electronics",
        "charger",
        "smart charger",
        "65w",
        "voltx",
        "usb"
      ]
    },

    "NDG-COS-000001": {
      recordId: "NDG-REC-2026-000005",
      productId: "NDG-COS-000001",
      barcode: "NDG-COS-000001",
      name: "GlowPure Face Cream",
      brand: "GlowPure",
      sku: "NDG-COS-000001",
      batch: "COS-LOT-2026-210",
      category: "Cosmetics",
      country: "France",
      origin: "France",
      manufacturer: "GlowPure Labs",
      issuer: "NetDAG Cosmetics Desk",
      created: "2026-07-04",
      integrity: "Submitted",
      trustStatus: "SUBMITTED",
      onchainId: "NDG-COS-000001",
      guardianScore: 62,
      status: "WARNING",
      risk: "Product Record Under Review",
      fraudStatus: "MEDIUM",
      conflictFlag: false,
      reviewRequired: true,
      evidence: {
        barcode: "User Scan",
        productName: "User Submission",
        ingredients: "Label OCR",
        manufacturer: "Unconfirmed"
      },
      keywords: [
        "cosmetics",
        "cream",
        "face cream",
        "glowpure",
        "beauty",
        "skin"
      ]
    },

    "NDG-INCOMPLETE-000001": {
  recordId: "NDG-REC-2026-000006",
  productId: "NDG-INCOMPLETE-000001",
  barcode: "NDG-INCOMPLETE-000001",
  name: "UrbanStep Running Shoe",
  brand: "UrbanStep",
  sku: "NDG-INCOMPLETE-000001",
  batch: "LOT-2026-0091",
  category: "Fashion",
  country: "Vietnam",
  origin: "Vietnam",
  manufacturer: "UrbanStep Footwear Ltd.",
  issuer: "NetDAG Provenance Desk",
  created: "2026-07-05",
  integrity: "Limited Evidence",
  trustStatus: "AUTO_VALIDATED",
  onchainId: "NDG-INCOMPLETE-000001",
  guardianScore: 72,
  status: "WARNING",
  risk: "Evidence Incomplete",
  fraudStatus: "LOW",
  conflictFlag: false,
  reviewRequired: false,
  certificateAvailable: true,
  evidence: {
    barcode: "Scan",
    productName: "Label",
    manufacturer: "Label"
  },
  keywords: ["shoe", "urbanstep", "fashion", "limited evidence"]
},

"NDG-NOCERT-000001": {
  recordId: "NDG-REC-2026-000007",
  productId: "NDG-NOCERT-000001",
  barcode: "NDG-NOCERT-000001",
  name: "ClearSkin Lotion",
  brand: "ClearSkin",
  sku: "NDG-NOCERT-000001",
  batch: "COS-LOT-2026-501",
  category: "Cosmetics",
  country: "France",
  origin: "France",
  manufacturer: "ClearSkin Labs",
  issuer: "NetDAG Cosmetics Desk",
  created: "2026-07-05",
  integrity: "Evidence Confirmed",
  trustStatus: "EVIDENCE_CONFIRMED",
  onchainId: "NDG-NOCERT-000001",
  guardianScore: 78,
  status: "WARNING",
  risk: "Certificate Missing",
  fraudStatus: "LOW",
  conflictFlag: false,
  reviewRequired: false,
  certificateAvailable: false,
  evidence: {
    barcode: "Scan",
    productName: "Label",
    manufacturer: "Label",
    origin: "Label"
  },
  keywords: ["cosmetics", "lotion", "clearskin", "certificate missing"]
},

"NDG-REVIEW-000001": {
  recordId: "NDG-REC-2026-000008",
  productId: "NDG-REVIEW-000001",
  barcode: "NDG-REVIEW-000001",
  name: "VoltMini Power Bank",
  brand: "VoltMini",
  sku: "NDG-REVIEW-000001",
  batch: "ELEC-LOT-2026-331",
  category: "Electronics",
  country: "China",
  origin: "China",
  manufacturer: "VoltMini Electronics",
  issuer: "NetDAG Electronics Desk",
  created: "2026-07-05",
  integrity: "Manual Review Required",
  trustStatus: "SUBMITTED",
  onchainId: "NDG-REVIEW-000001",
  guardianScore: 55,
  status: "WARNING",
  risk: "Manual Review Required",
  fraudStatus: "MEDIUM",
  conflictFlag: false,
  reviewRequired: true,
  certificateAvailable: true,
  evidence: {
    barcode: "User Scan",
    productName: "User Submission"
  },
  keywords: ["electronics", "power bank", "review required"]
},

"NDG-CONFLICT-000001": {
  recordId: "NDG-REC-2026-000009",
  productId: "NDG-CONFLICT-000001",
  barcode: "NDG-CONFLICT-000001",
  name: "Golden Harvest Rice",
  brand: "Golden Harvest",
  sku: "NDG-CONFLICT-000001",
  batch: "FOOD-LOT-2026-777",
  category: "Food",
  country: "Thailand",
  origin: "Vietnam",
  manufacturer: "Golden Harvest Foods",
  issuer: "NetDAG Food Desk",
  created: "2026-07-05",
  integrity: "Conflict Detected",
  trustStatus: "AUTO_VALIDATED",
  onchainId: "NDG-CONFLICT-000001",
  guardianScore: 44,
  status: "WARNING",
  risk: "Conflicting Origin Information",
  fraudStatus: "MEDIUM",
  conflictFlag: true,
  reviewRequired: true,
  certificateAvailable: true,
  evidence: {
    barcode: "Scan",
    productName: "Database",
    origin: "Conflicting Sources",
    manufacturer: "Label"
  },
  keywords: ["food", "rice", "conflict", "origin conflict"]
},

"NDG-FAKE-000001": {
  recordId: "NDG-REC-2026-000010",
  productId: "NDG-FAKE-000001",
  barcode: "NDG-FAKE-000001",
  name: "Premium Designer Bag",
  brand: "Unknown Luxury",
  sku: "NDG-FAKE-000001",
  batch: "FAKE-LOT-001",
  category: "Fashion",
  country: "Unknown",
  origin: "Unknown",
  manufacturer: "Unverified Manufacturer",
  issuer: "Unknown",
  created: "2026-07-05",
  integrity: "Counterfeit Risk",
  trustStatus: "SUBMITTED",
  onchainId: "NDG-FAKE-000001",
  guardianScore: 18,
  status: "FAILED",
  risk: "Counterfeit Risk Detected",
  fraudStatus: "HIGH",
  conflictFlag: true,
  reviewRequired: true,
  certificateAvailable: false,
  evidence: {
    barcode: "Suspicious Scan"
  },
  keywords: ["fake", "counterfeit", "luxury", "bag"]
},

"NDG-REVOKED-000001": {
  recordId: "NDG-REC-2026-000011",
  productId: "NDG-REVOKED-000001",
  barcode: "NDG-REVOKED-000001",
  name: "MedTrust Antibiotic 250mg",
  brand: "MedTrust",
  sku: "NDG-REVOKED-000001",
  batch: "MED-LOT-2026-999",
  category: "Medicine",
  country: "Germany",
  origin: "Germany",
  manufacturer: "MedTrust Pharma GmbH",
  issuer: "NetDAG Medicine Desk",
  created: "2026-07-05",
  integrity: "Certificate Revoked",
  trustStatus: "TRUSTED_PRODUCT",
  onchainId: "NDG-REVOKED-000001",
  guardianScore: 30,
  status: "FAILED",
  risk: "Certificate Revoked",
  fraudStatus: "HIGH",
  conflictFlag: false,
  reviewRequired: true,
  certificateAvailable: true,
  certificateRevoked: true,
  evidence: {
    barcode: "Scan",
    productName: "Manufacturer",
    manufacturer: "Manufacturer",
    certificate: "Revoked Certificate"
  },
  keywords: ["medicine", "antibiotic", "revoked", "medtrust"]
}

  }
};

